config/routes.rb
Obereg::Application.routes.draw do

  resources :orders

  resources :information

  resources :users

  resources :categories

  resources :pages

  resources :questions, :except => :destroy

  resources :articles, :except => [:index, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  get "pages/index"

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'delivery' => "pages#delivery", :as => :delivery

  root :to => "pages#index"

  namespace :admin do
    resources :categories
    resources :articles
    resources :pages
    resources :informations
  
      root :to => 'articles#index'
  end

end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin,@admin_page]) do |f| %>
  <% if @admin_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_page.errors.count, "error") %> prohibited this admin_page from being saved:</h2>

      <ul>
      <% @admin_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing admin_page</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@admin_page] %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Listing admin_pages</h1>

<table>
  <tr>
    <th>Page</th>
    <th>Main</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_pages.each do |admin_page| %>
  <tr>
    <td><%= admin_page.name %></td>
    <td><%= admin_page.content %></td>
    <td><%= link_to 'Show', [:admin,admin_page] %></td>
    <td><%= link_to 'Edit', edit_admin_page_path(admin_page) %></td>
    <td><%= link_to 'Destroy', [:admin,admin_page], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>New admin_page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Page:</b>
  <%= @admin_page.name %>
</p>

<p>
  <b>Main:</b>
  <%= @admin_page.content %>
</p>


<%= link_to 'Edit', edit_admin_page_path(@admin_page) %> |
<%= link_to 'Back', admin_pages_path %>