config/routes.rb
Obereg::Application.routes.draw do

  resources :orders

  resources :information

  resources :users

  resources :categories

  resources :pages

  resources :questions, :except => :destroy

  resources :articles, :except => [:index, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  get "pages/index"

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'delivery' => "pages#delivery", :as => :delivery

  root :to => "pages#index"

  namespace :admin do
    resources :categories
    resources :articles
    resources :pages
    resources :informations
  
      root :to => 'articles#index'
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :orders, :join_table => "articles_orders", :association_foreign_key => 'order_id'
  validates_presence_of :name, :short_description, :little_pic, :category_id, :price, :material
  scope :recent, order("created_at desc").limit(5)
  mount_before_save_uploader :name_pic, ImageUploader
  mount_before_save_uploader :little_pic, ImageUploader
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :login_required
  before_filter :get_categories
  # GET /admin/articles
  # GET /admin/articles.xml
  def index
    @admin_articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.xml
  def show
    @admin_article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /admin/articles/new
  # GET /admin/articles/new.xml
  def new
    @admin_article = Article.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /admin/articles/1/edit
  def edit
    @admin_article = Article.find(params[:id])
  end

  # POST /admin/articles
  # POST /admin/articles.xml
  def create
    @admin_article = Article.new(params[:article])

    respond_to do |format|
      if @admin_article.save
        format.html { redirect_to([:admin,@admin_article], :notice => 'Article was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /admin/articles/1
  # PUT /admin/articles/1.xml
  def update
    @admin_article = Article.find(params[:id])

    respond_to do |format|
      if @admin_article.update_attributes(params[:article])
        format.html { redirect_to([:admin,@admin_article], :notice => 'Article was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.xml
  def destroy
    @admin_article = Article.find(params[:id])
    @admin_article.destroy

    respond_to do |format|
      format.html { redirect_to(admin_articles_url) }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  inherit_resources
  before_filter :get_categories
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @page = 'product'
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    if params[:article_id]
      @article = Article.find(params[:article_id])
      session[:articles_id] ? session[:articles_id] << params[:article_id] : session[:articles_id] = [params[:article_id]]
      respond_to do |format|
        format.html { redirect_to(@article, :notice => 'Товар добавлен в корзину') }
      end
    else
      @article = Article.new
      respond_to do |format|
        format.html # new.html.erb
      end
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])
    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Товар создан') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
#  def update
#    @article = Article.find(params[:id])
#
#    respond_to do |format|
#      if @article.update_attributes(params[:id])
#        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
#        format.xml  { head :ok }
#      else
#        format.html { render :action => "edit" }
#        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end

  private

  def current_order
    @order = session[:order_id]
    Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:multipart => true}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Название" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Картинка с названием" %><br />
    <%= image_tag(@article.name_pic_url) if @article.name_pic? %>
    <%= f.file_field :name_pic %>
    <%= f.hidden_field :name_pic_cache %>
  </div>
  <div class="field">
    <%= f.label "Краткое описание" %><br />
    <%= f.text_area :short_description, :size => "100x3" %>
  </div>
  <div class="field">
    <%= f.label "Описание" %><br />
    <%= f.text_area :description, :size => "100x20" %>
  </div>
  <div class="field">
    <%= f.label "Размер" %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label "Материал" %><br />
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label "Картинка" %><br />
    <%= image_tag(@article.little_pic_url) if @article.little_pic? %>
    <%= f.file_field :little_pic %>
    <%= f.hidden_field :little_pic_cache %>
  </div>
  <div class="field">
    <%= f.label "Категория" %><br />
    <%= f.select :category_id, options_from_collection_for_select(@categories, :id, :name, @article.category_id) %>
  </div>
  <div class="field">
    <%= f.label "Цена" %><br />
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Little pic</th>
    <th>More pics</th>
    <th>Category</th>
    <th>Price</th>
    <th>Existence</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.name %></td>
    <td><%= article.description %></td>
    <td><%= article.little_pic %></td>
    <td><%= article.category %></td>
    <td><%= article.price %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="item">
  <div class="info">
    <%= notice %>
    <h1><%= image_tag @article.name_pic_url %></h1>
    <ul>
      <li><strong>Размер:</strong><%= @article.size %>.</li>
      <li><strong>Материал:</strong><%= @article.material %>.</li>
      <li><strong>Цена:</strong><%= @article.price %> p.</li>
      <li></li>
      <li><%= link_to 'Добавить товар в корзину', order_path(@article.id), :onclick => "alert('Товар добавлен в корзину.')" %></li>
    </ul>
    <div class="picture">
      <a href="#pic" title="Нажмите для увеличения">
        <%= image_tag @article.little_pic_url %>
      </a>
    </div>
  </div>
  <div id="pic" style="display: none; z-index: 1200;">
    <%= image_tag @article.little_pic_url, :size => "640x480"%>
  </div>
  <div class="desc">
    <h2>Описание:</h2>
    <div class="flexcroll" id="mycustomscroll_product">
      <%= @article.description %>
    </div>
  </div>
  <% if logged_in? %>
    <%= link_to 'Edit', edit_article_path(@article) %>
  <% end %>
  <%= link_to "Вернуться назад", :back, :class => "back-link" %>
</div>