config/routes.rb
Obereg::Application.routes.draw do

  resources :orders

  resources :information

  resources :users

  resources :categories

  resources :pages

  resources :questions, :except => :destroy

  resources :articles, :except => [:index, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  get "pages/index"

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'delivery' => "pages#delivery", :as => :delivery

  root :to => "pages#index"

  namespace :admin do
    resources :categories
    resources :articles
    resources :pages
    resources :informations
  
      root :to => 'articles#index'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates_presence_of :name
  mount_before_save_uploader :name_pic, ImageUploader
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :get_categories
  # GET /admin/categories
  # GET /admin/categories.xml
  def index
    @admin_categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_categories }
    end
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.xml
  def show
    @admin_category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_category }
    end
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.xml
  def new
    @admin_category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @admin_category = Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.xml
  def create
    @admin_category = Category.new(params[:category])

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to([:admin,@admin_category], :notice => 'Category was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.xml
  def update
    @admin_category = Category.find(params[:id])

    respond_to do |format|
      if @admin_category.update_attributes(params[:category])
        format.html { redirect_to([:admin,@admin_category], :notice => 'Category was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.xml
  def destroy
    @admin_category = Category.find(params[:id])
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to(admin_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  inherit_resources
  before_filter :get_categories

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @page = 'products'
    @category = Category.find(params[:id])
    @articles = @category.articles.page(params[:page]).per(3)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Картинка с названием" %><br />
    <%= image_tag(@category.name_pic_url) if @category.name_pic? %>
    <%= f.file_field :name_pic %>
    <%= f.hidden_field :name_pic_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= paginate @articles %>

<% @articles.each do |a|%>
<div class="items">
  <div class="item-field">
    <div class="item-pic"><%= image_tag(a.little_pic_url) %><span class="frame"><%= link_to nil, a, :class => "item-link" %></span></div>
    <div class="item-desc">
      <p><strong><%= link_to a.name, a %></strong></p>
      <p><%= a.short_description %></p>
    </div>
  </div>
</div>
<% end %>

<%= paginate @articles %>

<% if logged_in? %>
<%= link_to 'Новый товар', new_article_path %>
<% end %>