config/routes.rb
Obereg::Application.routes.draw do

  resources :orders

  resources :information

  resources :users

  resources :categories

  resources :pages

  resources :questions, :except => :destroy

  resources :articles, :except => [:index, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  get "pages/index"

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'delivery' => "pages#delivery", :as => :delivery

  root :to => "pages#index"

  namespace :admin do
    resources :categories
    resources :articles
    resources :pages
    resources :informations
  
      root :to => 'articles#index'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'fancyzoom.min' %>
  <%= javascript_include_tag 'flexcroll' %>
  <%= javascript_include_tag 'DD_belatedPNG_0.0.8a' %>
  <%= javascript_include_tag 'rails.validations' %>
  <%= csrf_meta_tag %>
  <title>Главная</title>

	<meta http-equiv="content-type" content="text/html; charset=UTF-8">

	<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="ie.css" />
	<![endif]-->

	<!--[if IE 6]>
		<script src="js/DD_belatedPNG_0.0.8a.js"></script>
		<script>
			DD_belatedPNG.fix('.wrap, .header h2, .content h1, .menu img, .header h2 a, .new h1, .new .contents, .counters-top, .order a, .item-pic img');
		</script>
	<![endif]-->
        <script type="text/javascript" charset="utf-8">
          $(document).ready(function() {
              $('div.picture a').fancyZoom({scaleImg: true, closeOnClick: true});
              $('#medium_box_link').fancyZoom({width:400, height:300});
              });
</script>
</head>
<body>
  
<!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body class=""> <!--<![endif]-->

<div class="wrap">
	<div class="header">
		<h1><a href="#">Славянское Сердце</a></h1>
		<h2><a href="#">Древнеславянская языческая мастерская</a></h2>
                <div class="order"><%= link_to 'Заказать', orders_path %></div>
	</div>
  <div class="menu">
    <ul>
      <li><%= link_to(image_tag("menu-home.png",:size => "150x47"), root_path) %></li>
      <li><%= link_to(image_tag("menu-info.png",:size => "150x47"), information_index_path) %></li>
      <li class="products"><%= image_tag("menu-products.png",:size => "150x47") %>
      <ul>
      <% @categories.each do |cat| %>
        <li><%= link_to cat.name, cat %></li>
      <% end %>
      </ul>
    </li>
      <li><%= link_to(image_tag("menu-contacts.png",:size => "150x47"), delivery_path) %></li>
      <li><%= link_to(image_tag("menu-faq.png",:size => "150x47"), questions_path) %></li>
    </ul>
  </div>
</div>

<%= index_or_not(@page) %>
  <div class="content">
<%= yield %>
  </div>
  <div class="content-after"></div>
  <div class="new">
    <h1>Новинки</h1>
    <div class="contents">
      <ul>
        <% @new_articles.each do |a| %>
          <li><%= link_to(image_tag(a.little_pic_url, :size => "160x120"), a )%></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="friends">
    <h1>Друзья сайта</h1>
    <div class="contents"></div>
  </div>
  <div class="counters-top"></div>
  <div class="counters">

  </div>
</div>
    <!--<div id="categories">Товары</div>
    <div id="popup-categories"  style="display: none; height: auto;">
    </div>--!>
    <% if logged_in? -%>
    -----------
    <%= link_to 'Добавить категорию', new_category_path, :class => "simple_link" %>
    <% end %>
  </div>
  <script type="text/javascript">
    $(document).ready(function(){
        $('li.products').hover(
          function() { $('ul', this).css('display', 'block'); },
          function() { $('ul', this).css('display', 'none'); }
          );
        });
  </script>
<% if logged_in? -%>
  <div id="user-bar-action"  >(<%= link_to "Стать простым пользователем", logout_path, { :title => "Log out" }, :class => "simple_link"    %>)</div>
<% end -%>

</body>
</html>